name: CI Workflow
run-name: CI Workflow from the ${{ github.head_ref }} branch
on: pull_request

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        
      - name: Setup the environment
        run: ./scripts/set-up-environment.sh
        
      - name: Build the application for testing
        run: ./scripts/build-for-testing.sh
        
      - name: Archive Build
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: DerivedData/Build/Products/Debug-iphonesimulator/SpaceLaunches.app

      - name: Archive Runner
        uses: actions/upload-artifact@v4
        with:
          name: Runner
          path: DerivedData/Build/Products/Debug-iphonesimulator/SpaceLaunches-Runner.app

  unit_tests:
    needs: build
    runs-on: macos-14
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup the environment
        run: ./scripts/set-up-environment.sh

      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: Build
          path: DerivedData/Build/Products/Debug-iphonesimulator/SpaceLaunches.app

      - name: Download Runner
        uses: actions/download-artifact@v4
        with:
          name: Runner
          path: DerivedData/Build/Products/Debug-iphonesimulator/SpaceLaunches-Runner.app

      - name: Run unit tests
        run: ./scripts/run-unit-tests-without-building.sh
